version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.6
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.authc.api_key.enabled=false
      - network.host=0.0.0.0
      - http.host=0.0.0.0
    network_mode: "host"
    ports:
      - "9200:9200"
      - "9300:9300"
    mem_limit: 4g
    restart: unless-stopped
    stdin_open: true
    tty: true
  
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    network_mode: "host"
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
